ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_tipo_job_check;
ALTER TABLE jobs ADD CONSTRAINT jobs_tipo_job_check 
CHECK (tipo_job IN ('SYNC_COMPROBANTES', 'ENVIAR_A_ORDS', 'DESCARGAR_XML', 'SYNC_FACTURAS_VIRTUALES', 'RECONCILIAR_CUENTA', 'IMPORTAR_PROCESADOR', 'SYNC_BANCO_PORTAL', 'EMITIR_SIFEN', 'CONSULTAR_SIFEN', 'SEND_INVOICE_EMAIL'));
