-- Migration 031: Update plan feature keys to match current feature definitions
-- Adds new feature keys while preserving existing ones

UPDATE plans SET features = features || '{
  "comprobantes": true,
  "marangatu_sync": true,
  "ords_sync": false,
  "clasificacion": false,
  "exportacion_xlsx": false,
  "exportacion_pdf": false,
  "exportacion_csv": true,
  "exportacion_json": false,
  "exportacion_txt": false,
  "notificaciones": true,
  "forecast": false,
  "roles_custom": false,
  "virtual_invoices": false,
  "usuarios_ilimitados": false,
  "csv_schemas_custom": false,
  "facturacion_electronica": false,
  "api_tokens": false,
  "alertas": false,
  "anomalias": false,
  "metricas": false,
  "webhooks": false,
  "whitelabel": false,
  "conciliacion": false,
  "auditoria": false
}'::jsonb WHERE nombre = 'FREE';

UPDATE plans SET features = features || '{
  "comprobantes": true,
  "marangatu_sync": true,
  "ords_sync": true,
  "clasificacion": true,
  "exportacion_xlsx": true,
  "exportacion_pdf": true,
  "exportacion_csv": true,
  "exportacion_json": true,
  "exportacion_txt": false,
  "notificaciones": true,
  "forecast": false,
  "roles_custom": false,
  "virtual_invoices": false,
  "usuarios_ilimitados": false,
  "csv_schemas_custom": false,
  "facturacion_electronica": false,
  "api_tokens": true,
  "alertas": true,
  "anomalias": true,
  "metricas": true,
  "webhooks": true,
  "whitelabel": false,
  "conciliacion": true,
  "auditoria": false
}'::jsonb WHERE nombre = 'PRO';

UPDATE plans SET features = features || '{
  "comprobantes": true,
  "marangatu_sync": true,
  "ords_sync": true,
  "clasificacion": true,
  "exportacion_xlsx": true,
  "exportacion_pdf": true,
  "exportacion_csv": true,
  "exportacion_json": true,
  "exportacion_txt": true,
  "notificaciones": true,
  "forecast": true,
  "roles_custom": true,
  "virtual_invoices": true,
  "usuarios_ilimitados": true,
  "csv_schemas_custom": true,
  "facturacion_electronica": true,
  "api_tokens": true,
  "alertas": true,
  "anomalias": true,
  "metricas": true,
  "webhooks": true,
  "whitelabel": true,
  "conciliacion": true,
  "auditoria": true
}'::jsonb WHERE nombre = 'ENTERPRISE';
