-- Migration 052: Actividades económicas CIIU Rev. 4 (fuente: ONU/DNIT)

CREATE TABLE IF NOT EXISTS sifen_ref_actividades_economicas (
  codigo VARCHAR(10) PRIMARY KEY,
  descripcion VARCHAR(300) NOT NULL
);

INSERT INTO sifen_ref_actividades_economicas (codigo, descripcion) VALUES
  ('0111', 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas'),
  ('0112', 'Cultivo de arroz'),
  ('0113', 'Cultivo de hortalizas y melones, raíces y tubérculos'),
  ('0114', 'Cultivo de caña de azúcar'),
  ('0115', 'Cultivo de tabaco'),
  ('0116', 'Cultivo de plantas de fibra'),
  ('0119', 'Cultivo de otras plantas no perennes'),
  ('0121', 'Cultivo de uva'),
  ('0122', 'Cultivo de frutas tropicales y subtropicales'),
  ('0123', 'Cultivo de cítricos'),
  ('0124', 'Cultivo de frutas de pepita y de hueso'),
  ('0125', 'Cultivo de otros frutos y nueces de árboles y arbustos'),
  ('0126', 'Cultivo de frutos oleaginosos'),
  ('0127', 'Cultivo de plantas con las que se preparan bebidas'),
  ('0128', 'Cultivo de especias y de plantas aromáticas, medicinales y farmacéuticas'),
  ('0129', 'Cultivo de otras plantas perennes'),
  ('0130', 'Propagación de plantas'),
  ('0141', 'Cría de ganado bovino y búfalos'),
  ('0142', 'Cría de caballos y otros equinos'),
  ('0143', 'Cría de camellos y otros camélidos'),
  ('0144', 'Cría de ovejas y cabras'),
  ('0145', 'Cría de cerdos'),
  ('0146', 'Cría de aves de corral'),
  ('0149', 'Cría de otros animales'),
  ('0150', 'Cultivo de productos agrícolas en combinación con la cría de animales (explotación mixta)'),
  ('0161', 'Actividades de apoyo a la agricultura'),
  ('0162', 'Actividades de apoyo a la ganadería'),
  ('0163', 'Actividades poscosecha'),
  ('0164', 'Tratamiento de semillas para propagación'),
  ('0170', 'Caza ordinaria y mediante trampas y actividades de servicios conexas'),
  ('0210', 'Silvicultura y otras actividades forestales'),
  ('0220', 'Extracción de madera'),
  ('0230', 'Recolección de productos forestales distintos de la madera'),
  ('0240', 'Servicios de apoyo a la silvicultura'),
  ('0311', 'Pesca marítima'),
  ('0312', 'Pesca de agua dulce'),
  ('0321', 'Acuicultura marina'),
  ('0322', 'Acuicultura de agua dulce'),
  ('0510', 'Extracción de carbón de piedra'),
  ('0520', 'Extracción de lignito'),
  ('0610', 'Extracción de petróleo crudo'),
  ('0620', 'Extracción de gas natural'),
  ('0710', 'Extracción de minerales de hierro'),
  ('0721', 'Extracción de minerales de uranio y torio'),
  ('0729', 'Extracción de otros minerales metalíferos no ferrosos'),
  ('0810', 'Extracción de piedra, arena y arcilla'),
  ('0891', 'Extracción de minerales para la fabricación de abonos y productos químicos'),
  ('0892', 'Extracción de turba'),
  ('0893', 'Extracción de sal'),
  ('0899', 'Explotación de otras minas y canteras n.c.p.'),
  ('0910', 'Actividades de apoyo para la extracción de petróleo y gas natural'),
  ('0990', 'Actividades de apoyo para otras actividades de explotación de minas y canteras'),
  ('1010', 'Elaboración y conservación de carne'),
  ('1020', 'Elaboración y conservación de pescado, crustáceos y moluscos'),
  ('1030', 'Elaboración y conservación de frutas, legumbres y hortalizas'),
  ('1040', 'Elaboración de aceites y grasas de origen vegetal y animal'),
  ('1050', 'Elaboración de productos lácteos'),
  ('1061', 'Elaboración de productos de molinería'),
  ('1062', 'Elaboración de almidones y productos derivados del almidón'),
  ('1071', 'Elaboración de productos de panadería'),
  ('1072', 'Elaboración de azúcar'),
  ('1073', 'Elaboración de cacao y chocolate y de productos de confitería'),
  ('1074', 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares'),
  ('1075', 'Elaboración de comidas y platos preparados'),
  ('1079', 'Elaboración de otros productos alimenticios n.c.p.'),
  ('1080', 'Elaboración de piensos preparados para animales'),
  ('1101', 'Destilación, rectificación y mezcla de bebidas alcohólicas'),
  ('1102', 'Elaboración de vinos'),
  ('1103', 'Elaboración de bebidas malteadas y de malta'),
  ('1104', 'Elaboración de bebidas no alcohólicas; producción de aguas minerales y otras aguas embotelladas'),
  ('1200', 'Elaboración de productos de tabaco'),
  ('1311', 'Preparación e hilatura de fibras textiles'),
  ('1312', 'Tejedura de productos textiles'),
  ('1313', 'Acabado de productos textiles'),
  ('1391', 'Fabricación de tejidos de punto y ganchillo'),
  ('1392', 'Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir'),
  ('1393', 'Fabricación de tapices y alfombras'),
  ('1394', 'Fabricación de cuerdas, cordeles, bramantes y redes'),
  ('1399', 'Fabricación de otros productos textiles n.c.p.'),
  ('1410', 'Fabricación de prendas de vestir, excepto prendas de piel'),
  ('1420', 'Fabricación de artículos de piel'),
  ('1430', 'Fabricación de artículos de punto y ganchillo'),
  ('1511', 'Curtido y adobo de cueros; adobo y teñido de pieles'),
  ('1512', 'Fabricación de maletas, bolsos de mano y artículos similares, y de artículos de talabartería y guarnicionería'),
  ('1520', 'Fabricación de calzado'),
  ('1610', 'Aserrado y acepilladura de madera'),
  ('1621', 'Fabricación de hojas de madera para enchapado y tableros a base de madera'),
  ('1622', 'Fabricación de partes y piezas de carpintería para edificios y construcciones'),
  ('1623', 'Fabricación de recipientes de madera'),
  ('1629', 'Fabricación de otros productos de madera; fabricación de artículos de corcho, paja y materiales trenzables'),
  ('1701', 'Fabricación de pasta de madera, papel y cartón'),
  ('1702', 'Fabricación de papel y cartón ondulado y de envases de papel y cartón'),
  ('1709', 'Fabricación de otros artículos de papel y cartón'),
  ('1811', 'Impresión'),
  ('1812', 'Actividades de servicios relacionadas con la impresión'),
  ('1820', 'Reproducción de grabaciones'),
  ('1910', 'Fabricación de productos de hornos de coque'),
  ('1920', 'Fabricación de productos de la refinación del petróleo'),
  ('2011', 'Fabricación de sustancias químicas básicas'),
  ('2012', 'Fabricación de abonos y compuestos de nitrógeno'),
  ('2013', 'Fabricación de plásticos y caucho sintético en formas primarias'),
  ('2021', 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario'),
  ('2022', 'Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas'),
  ('2023', 'Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador'),
  ('2029', 'Fabricación de otros productos químicos n.c.p.'),
  ('2030', 'Fabricación de fibras artificiales'),
  ('2100', 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico'),
  ('2211', 'Fabricación de cubiertas y cámaras de caucho; recauchutado y renovación de cubiertas de caucho'),
  ('2219', 'Fabricación de otros productos de caucho'),
  ('2220', 'Fabricación de productos de plástico'),
  ('2310', 'Fabricación de vidrio y productos de vidrio'),
  ('2391', 'Fabricación de productos refractarios'),
  ('2392', 'Fabricación de materiales de construcción de arcilla'),
  ('2393', 'Fabricación de otros productos de porcelana y de cerámica'),
  ('2394', 'Fabricación de cemento, cal y yeso'),
  ('2395', 'Fabricación de artículos de hormigón, cemento y yeso'),
  ('2396', 'Corte, talla y acabado de la piedra'),
  ('2399', 'Fabricación de otros productos minerales no metálicos n.c.p.'),
  ('2410', 'Industrias básicas de hierro y acero'),
  ('2420', 'Fabricación de productos primarios de metales preciosos y otros metales no ferrosos'),
  ('2431', 'Fundición de hierro y acero'),
  ('2432', 'Fundición de metales no ferrosos'),
  ('2511', 'Fabricación de productos metálicos para uso estructural'),
  ('2512', 'Fabricación de tanques, depósitos y recipientes de metal'),
  ('2513', 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central'),
  ('2520', 'Fabricación de armas y municiones'),
  ('2591', 'Forja, prensado, estampado y laminado de metales; pulvimetalurgia'),
  ('2592', 'Tratamiento y revestimiento de metales; maquinado'),
  ('2593', 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería'),
  ('2599', 'Fabricación de otros productos elaborados de metal n.c.p.'),
  ('2610', 'Fabricación de componentes y tableros electrónicos'),
  ('2620', 'Fabricación de ordenadores y equipo periférico'),
  ('2630', 'Fabricación de equipo de comunicaciones'),
  ('2640', 'Fabricación de aparatos electrónicos de consumo'),
  ('2651', 'Fabricación de equipo de medición, prueba, navegación y control'),
  ('2652', 'Fabricación de relojes'),
  ('2660', 'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico'),
  ('2670', 'Fabricación de instrumentos ópticos y equipo fotográfico'),
  ('2680', 'Fabricación de soportes magnéticos y ópticos'),
  ('2710', 'Fabricación de motores, generadores y transformadores eléctricos y aparatos de distribución y control de la energía eléctrica'),
  ('2720', 'Fabricación de pilas, baterías y acumuladores'),
  ('2731', 'Fabricación de cables de fibra óptica'),
  ('2732', 'Fabricación de otros hilos y cables eléctricos'),
  ('2733', 'Fabricación de dispositivos de cableado'),
  ('2740', 'Fabricación de equipo eléctrico de iluminación'),
  ('2750', 'Fabricación de aparatos de uso doméstico'),
  ('2790', 'Fabricación de otros tipos de equipo eléctrico'),
  ('2811', 'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas'),
  ('2812', 'Fabricación de equipo de propulsión de fluidos'),
  ('2813', 'Fabricación de otras bombas, compresores, grifos y válvulas'),
  ('2814', 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión'),
  ('2815', 'Fabricación de hornos, hogares y quemadores'),
  ('2816', 'Fabricación de equipo de elevación y manipulación'),
  ('2817', 'Fabricación de maquinaria y equipo de oficina (excepto ordenadores y equipo periférico)'),
  ('2818', 'Fabricación de herramientas de mano motorizadas'),
  ('2819', 'Fabricación de otros tipos de maquinaria de uso general'),
  ('2821', 'Fabricación de maquinaria agropecuaria y forestal'),
  ('2822', 'Fabricación de maquinaria para la conformación de metales y de máquinas herramienta'),
  ('2823', 'Fabricación de maquinaria metalúrgica'),
  ('2824', 'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción'),
  ('2825', 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco'),
  ('2826', 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros'),
  ('2829', 'Fabricación de otros tipos de maquinaria de uso especial'),
  ('2910', 'Fabricación de vehículos automotores'),
  ('2920', 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques'),
  ('2930', 'Fabricación de partes, piezas y accesorios para vehículos automotores'),
  ('3011', 'Construcción de buques y estructuras flotantes'),
  ('3012', 'Construcción de embarcaciones de recreo y de deporte'),
  ('3020', 'Fabricación de locomotoras y material rodante'),
  ('3030', 'Fabricación de aeronaves, naves espaciales y maquinaria conexa'),
  ('3040', 'Fabricación de vehículos militares de combate'),
  ('3091', 'Fabricación de motocicletas'),
  ('3092', 'Fabricación de bicicletas y de sillones de ruedas para inválidos'),
  ('3099', 'Fabricación de otros tipos de equipo de transporte n.c.p.'),
  ('3100', 'Fabricación de muebles'),
  ('3211', 'Fabricación de joyas y artículos conexos'),
  ('3212', 'Fabricación de bisutería y artículos conexos'),
  ('3220', 'Fabricación de instrumentos de música'),
  ('3230', 'Fabricación de artículos de deporte'),
  ('3240', 'Fabricación de juegos y juguetes'),
  ('3250', 'Fabricación de instrumentos y materiales médicos y odontológicos'),
  ('3290', 'Otras industrias manufactureras n.c.p.'),
  ('3311', 'Reparación de productos elaborados de metal'),
  ('3312', 'Reparación de maquinaria'),
  ('3313', 'Reparación de equipo electrónico y óptico'),
  ('3314', 'Reparación de equipo eléctrico'),
  ('3315', 'Reparación de equipo de transporte, excepto vehículos automotores'),
  ('3319', 'Reparación de otros tipos de equipo'),
  ('3320', 'Instalación de maquinaria y equipo industriales'),
  ('3510', 'Generación, transmisión y distribución de energía eléctrica'),
  ('3520', 'Fabricación de gas; distribución de combustibles gaseosos por tuberías'),
  ('3530', 'Suministro de vapor y de aire acondicionado'),
  ('3600', 'Captación, tratamiento y distribución de agua'),
  ('3700', 'Evacuación de aguas residuales'),
  ('3811', 'Recogida de desechos no peligrosos'),
  ('3812', 'Recogida de desechos peligrosos'),
  ('3821', 'Tratamiento y eliminación de desechos no peligrosos'),
  ('3822', 'Tratamiento y eliminación de desechos peligrosos'),
  ('3830', 'Recuperación de materiales'),
  ('3900', 'Actividades de descontaminación y otros servicios de gestión de desechos'),
  ('4100', 'Construcción de edificios'),
  ('4210', 'Construcción de carreteras y vías de ferrocarril'),
  ('4220', 'Construcción de proyectos de servicio público'),
  ('4290', 'Construcción de otras obras de ingeniería civil'),
  ('4311', 'Demolición'),
  ('4312', 'Preparación del terreno'),
  ('4321', 'Instalaciones eléctricas'),
  ('4322', 'Instalaciones de fontanería, calefacción y aire acondicionado'),
  ('4329', 'Otras instalaciones para obras de construcción'),
  ('4330', 'Terminación y acabado de edificios'),
  ('4390', 'Otras actividades especializadas de construcción'),
  ('4510', 'Venta de vehículos automotores'),
  ('4520', 'Mantenimiento y reparación de vehículos automotores'),
  ('4530', 'Venta de partes, piezas y accesorios para vehículos automotores'),
  ('4540', 'Venta, mantenimiento y reparación de motocicletas y sus partes, piezas y accesorios'),
  ('4610', 'Venta al por mayor a cambio de una retribución o por contrata'),
  ('4620', 'Venta al por mayor de materias primas agropecuarias y animales vivos'),
  ('4630', 'Venta al por mayor de alimentos, bebidas y tabaco'),
  ('4641', 'Venta al por mayor de productos textiles, prendas de vestir y calzado'),
  ('4649', 'Venta al por mayor de otros enseres domésticos'),
  ('4651', 'Venta al por mayor de ordenadores, equipo periférico y programas de informática'),
  ('4652', 'Venta al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones'),
  ('4653', 'Venta al por mayor de maquinaria, equipo y materiales agropecuarios'),
  ('4659', 'Venta al por mayor de otros tipos de maquinaria y equipo'),
  ('4661', 'Venta al por mayor de combustibles sólidos, líquidos y gaseosos y productos conexos'),
  ('4662', 'Venta al por mayor de metales y minerales metalíferos'),
  ('4663', 'Venta al por mayor de materiales de construcción, artículos de ferretería y equipo y materiales de fontanería y calefacción'),
  ('4669', 'Venta al por mayor de desperdicios, desechos y chatarra y otros productos n.c.p.'),
  ('4690', 'Venta al por mayor no especializada'),
  ('4711', 'Venta al por menor en comercios no especializados con predominio de la venta de alimentos, bebidas o tabaco'),
  ('4719', 'Otras actividades de venta al por menor en comercios no especializados'),
  ('4721', 'Venta al por menor de alimentos en comercios especializados'),
  ('4722', 'Venta al por menor de bebidas en comercios especializados'),
  ('4723', 'Venta al por menor de productos de tabaco en comercios especializados'),
  ('4730', 'Venta al por menor de combustibles para vehículos automotores en comercios especializados'),
  ('4741', 'Venta al por menor de ordenadores, equipo periférico, programas de informática y equipo de telecomunicaciones en comercios especializados'),
  ('4742', 'Venta al por menor de equipo de sonido y de video en comercios especializados'),
  ('4751', 'Venta al por menor de productos textiles en comercios especializados'),
  ('4752', 'Venta al por menor de artículos de ferretería, pinturas y productos de vidrio en comercios especializados'),
  ('4753', 'Venta al por menor de tapices, alfombras y cubrimientos para paredes y pisos en comercios especializados'),
  ('4759', 'Venta al por menor de aparatos eléctricos de uso doméstico, muebles, equipo de iluminación y otros enseres domésticos en comercios especializados'),
  ('4761', 'Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados'),
  ('4762', 'Venta al por menor de grabaciones de música y de vídeo en comercios especializados'),
  ('4763', 'Venta al por menor de equipo de deporte en comercios especializados'),
  ('4764', 'Venta al por menor de juegos y juguetes en comercios especializados'),
  ('4771', 'Venta al por menor de prendas de vestir, calzado y artículos de cuero en comercios especializados'),
  ('4772', 'Venta al por menor de productos farmacéuticos y médicos, cosméticos y artículos de tocador en comercios especializados'),
  ('4773', 'Venta al por menor de otros productos nuevos en comercios especializados'),
  ('4774', 'Venta al por menor de artículos de segunda mano'),
  ('4781', 'Venta al por menor de alimentos, bebidas y tabaco en puestos de venta y mercados'),
  ('4782', 'Venta al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y mercados'),
  ('4789', 'Venta al por menor de otros productos en puestos de venta y mercados'),
  ('4791', 'Venta al por menor por correo y por Internet'),
  ('4799', 'Otras actividades de venta al por menor no realizadas en comercios, puestos de venta o mercados'),
  ('4911', 'Transporte interurbano de pasajeros por ferrocarril'),
  ('4912', 'Transporte de carga por ferrocarril'),
  ('4921', 'Transporte urbano y suburbano de pasajeros por vía terrestre'),
  ('4922', 'Otras actividades de transporte por vía terrestre'),
  ('4923', 'Transporte de carga por carretera'),
  ('4930', 'Transporte por tuberías'),
  ('5011', 'Transporte de pasajeros marítimo y de cabotaje'),
  ('5012', 'Transporte de carga marítimo y de cabotaje'),
  ('5021', 'Transporte de pasajeros por vías de navegación interiores'),
  ('5022', 'Transporte de carga por vías de navegación interiores'),
  ('5110', 'Transporte de pasajeros por vía aérea'),
  ('5120', 'Transporte de carga por vía aérea'),
  ('5210', 'Almacenamiento y depósito'),
  ('5221', 'Actividades de servicios vinculadas al transporte terrestre'),
  ('5222', 'Actividades de servicios vinculadas al transporte acuático'),
  ('5223', 'Actividades de servicios vinculadas al transporte aéreo'),
  ('5224', 'Manipulación de la carga'),
  ('5229', 'Otras actividades de apoyo al transporte'),
  ('5310', 'Actividades postales'),
  ('5320', 'Actividades de mensajería'),
  ('5510', 'Actividades de alojamiento para estancias cortas'),
  ('5520', 'Actividades de campamentos, parques de vehículos recreativos y parques de caravanas'),
  ('5590', 'Otras actividades de alojamiento'),
  ('5610', 'Actividades de restaurantes y de servicio móvil de comidas'),
  ('5621', 'Suministro de comidas por encargo'),
  ('5629', 'Otras actividades de servicio de comidas'),
  ('5630', 'Actividades de servicio de bebidas'),
  ('5811', 'Edición de libros'),
  ('5812', 'Edición de directorios y listas de correo'),
  ('5813', 'Edición de periódicos, revistas y otras publicaciones periódicas'),
  ('5819', 'Otras actividades de edición'),
  ('5820', 'Edición de programas informáticos'),
  ('5911', 'Actividades de producción de películas cinematográficas, vídeos y programas de televisión'),
  ('5912', 'Actividades de postproducción de películas cinematográficas, vídeos y programas de televisión'),
  ('5913', 'Actividades de distribución de películas cinematográficas, vídeos y programas de televisión'),
  ('5914', 'Actividades de exhibición de películas cinematográficas y cintas de vídeo'),
  ('5920', 'Actividades de grabación de sonido y edición de música'),
  ('6010', 'Transmisiones de radio'),
  ('6020', 'Programación y transmisiones de televisión'),
  ('6110', 'Actividades de telecomunicaciones alámbricas'),
  ('6120', 'Actividades de telecomunicaciones inalámbricas'),
  ('6130', 'Actividades de telecomunicaciones por satélite'),
  ('6190', 'Otras actividades de telecomunicaciones'),
  ('6201', 'Programación informática'),
  ('6202', 'Consultoría de informática y gestión de instalaciones informáticas'),
  ('6209', 'Otras actividades de tecnología de la información y de servicios informáticos'),
  ('6311', 'Procesamiento de datos, hospedaje y actividades conexas'),
  ('6312', 'Portales web'),
  ('6391', 'Actividades de agencias de noticias'),
  ('6399', 'Otras actividades de servicios de información n.c.p.'),
  ('6411', 'Banca central'),
  ('6419', 'Otros tipos de intermediación monetaria'),
  ('6420', 'Actividades de sociedades de cartera'),
  ('6430', 'Fondos y sociedades de inversión y entidades financieras similares'),
  ('6491', 'Arrendamiento financiero'),
  ('6492', 'Otras actividades de concesión de crédito'),
  ('6499', 'Otras actividades de servicios financieros, excepto las de seguros y fondos de pensiones, n.c.p.'),
  ('6511', 'Seguros de vida'),
  ('6512', 'Seguros generales'),
  ('6520', 'Reaseguros'),
  ('6530', 'Fondos de pensiones'),
  ('6611', 'Administración de mercados financieros'),
  ('6612', 'Corretaje de valores y de contratos de productos básicos'),
  ('6619', 'Otras actividades auxiliares de las actividades de servicios financieros'),
  ('6621', 'Evaluación de riesgos y daños'),
  ('6622', 'Actividades de agentes y corredores de seguros'),
  ('6629', 'Otras actividades auxiliares de las actividades de seguros y fondos de pensiones'),
  ('6630', 'Actividades de gestión de fondos'),
  ('6810', 'Actividades inmobiliarias realizadas con bienes propios o arrendados'),
  ('6820', 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata'),
  ('6910', 'Actividades jurídicas'),
  ('6920', 'Actividades de contabilidad, teneduría de libros y auditoría; consultoría fiscal'),
  ('7010', 'Actividades de oficinas principales'),
  ('7020', 'Actividades de consultoría de gestión'),
  ('7110', 'Actividades de arquitectura e ingeniería y actividades conexas de consultoría técnica'),
  ('7120', 'Ensayos y análisis técnicos'),
  ('7210', 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería'),
  ('7220', 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades'),
  ('7310', 'Publicidad'),
  ('7320', 'Estudios de mercado y encuestas de opinión pública'),
  ('7410', 'Actividades especializadas de diseño'),
  ('7420', 'Actividades de fotografía'),
  ('7490', 'Otras actividades profesionales, científicas y técnicas n.c.p.'),
  ('7500', 'Actividades veterinarias'),
  ('7710', 'Alquiler y arrendamiento de vehículos automotores'),
  ('7721', 'Alquiler y arrendamiento de equipo recreativo y deportivo'),
  ('7722', 'Alquiler de cintas de vídeo y discos'),
  ('7729', 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos'),
  ('7730', 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles'),
  ('7740', 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor'),
  ('7810', 'Actividades de agencias de empleo'),
  ('7820', 'Actividades de agencias de empleo temporal'),
  ('7830', 'Otras actividades de dotación de recursos humanos'),
  ('7911', 'Actividades de agencias de viajes'),
  ('7912', 'Actividades de operadores turísticos'),
  ('7990', 'Otros servicios de reservas y actividades conexas'),
  ('8010', 'Actividades de seguridad privada'),
  ('8020', 'Actividades de servicios de sistemas de seguridad'),
  ('8030', 'Actividades de investigación'),
  ('8110', 'Actividades combinadas de apoyo a instalaciones'),
  ('8121', 'Limpieza general de edificios'),
  ('8129', 'Otras actividades de limpieza de edificios y de instalaciones industriales'),
  ('8130', 'Actividades de paisajismo y servicios de mantenimiento conexos'),
  ('8211', 'Actividades combinadas de servicios administrativos de oficina'),
  ('8219', 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo de oficina'),
  ('8220', 'Actividades de centros de llamadas'),
  ('8230', 'Organización de convenciones y exposiciones comerciales'),
  ('8291', 'Actividades de agencias de cobro y agencias de calificación crediticia'),
  ('8292', 'Actividades de envasado y empaquetado'),
  ('8299', 'Otras actividades de servicios de apoyo a las empresas n.c.p.'),
  ('8411', 'Actividades de la administración pública en general'),
  ('8412', 'Regulación de las actividades de organismos que prestan servicios sanitarios, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social'),
  ('8413', 'Regulación y facilitación de la actividad económica'),
  ('8421', 'Relaciones exteriores'),
  ('8422', 'Actividades de defensa'),
  ('8423', 'Actividades de mantenimiento del orden público y de seguridad'),
  ('8430', 'Actividades de planes de seguridad social de afiliación obligatoria'),
  ('8510', 'Enseñanza preescolar y primaria'),
  ('8521', 'Enseñanza secundaria de formación general'),
  ('8522', 'Enseñanza secundaria de formación técnica y profesional'),
  ('8530', 'Enseñanza superior'),
  ('8541', 'Enseñanza deportiva y recreativa'),
  ('8542', 'Enseñanza cultural'),
  ('8549', 'Otros tipos de enseñanza n.c.p.'),
  ('8550', 'Actividades de apoyo a la enseñanza'),
  ('8610', 'Actividades de hospitales'),
  ('8620', 'Actividades de médicos y odontólogos'),
  ('8690', 'Otras actividades de atención de la salud humana'),
  ('8710', 'Actividades de atención de enfermería en instituciones'),
  ('8720', 'Actividades de atención en instituciones para personas con retraso mental, enfermos mentales y toxicómanos'),
  ('8730', 'Actividades de atención en instituciones para personas de edad y personas con discapacidad'),
  ('8790', 'Otras actividades de atención en instituciones'),
  ('8810', 'Actividades de asistencia social sin alojamiento para personas de edad y personas con discapacidad'),
  ('8890', 'Otras actividades de asistencia social sin alojamiento'),
  ('9000', 'Actividades creativas, artísticas y de entretenimiento'),
  ('9101', 'Actividades de librerías y archivos'),
  ('9102', 'Actividades de museos y conservación de lugares y edificios históricos'),
  ('9103', 'Actividades de jardines botánicos y zoológicos y de reservas naturales'),
  ('9200', 'Actividades de juegos de azar y apuestas'),
  ('9311', 'Gestión de instalaciones deportivas'),
  ('9312', 'Actividades de clubes deportivos'),
  ('9319', 'Otras actividades deportivas'),
  ('9321', 'Actividades de parques de atracciones y parques temáticos'),
  ('9329', 'Otras actividades de esparcimiento y recreativas n.c.p.'),
  ('9411', 'Actividades de asociaciones empresariales y de empleadores'),
  ('9412', 'Actividades de asociaciones profesionales'),
  ('9420', 'Actividades de sindicatos'),
  ('9491', 'Actividades de organizaciones religiosas'),
  ('9492', 'Actividades de organizaciones políticas'),
  ('9499', 'Actividades de otras asociaciones n.c.p.'),
  ('9511', 'Reparación de ordenadores y equipo periférico'),
  ('9512', 'Reparación de equipo de comunicaciones'),
  ('9521', 'Reparación de aparatos electrónicos de consumo'),
  ('9522', 'Reparación de aparatos de uso doméstico y equipo doméstico y de jardinería'),
  ('9523', 'Reparación de calzado y de artículos de cuero'),
  ('9524', 'Reparación de muebles y accesorios domésticos'),
  ('9529', 'Reparación de otros efectos personales y enseres domésticos'),
  ('9601', 'Lavado y limpieza, incluida la limpieza en seco, de productos textiles y de piel'),
  ('9602', 'Peluquería y otros tratamientos de belleza'),
  ('9603', 'Pompas fúnebres y actividades conexas'),
  ('9609', 'Otras actividades de servicios personales n.c.p.'),
  ('9700', 'Actividades de los hogares como empleadores de personal doméstico'),
  ('9810', 'Actividades no diferenciadas de los hogares como productores de bienes para uso propio'),
  ('9820', 'Actividades no diferenciadas de los hogares como productores de servicios para uso propio'),
  ('9900', 'Actividades de organizaciones y órganos extraterritoriales')
ON CONFLICT (codigo) DO UPDATE SET descripcion = EXCLUDED.descripcion;
