import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    // ── Principal ──
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: '',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'comprobantes',
        path: '/comprobantes',
        title: 'Comprobantes',
        translateKey: '',
        icon: 'comprobantes',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        spiPermiso: 'comprobantes:ver',
        subMenu: [],
    },
    {
        key: 'empresas',
        path: '/empresas',
        title: 'Empresas',
        translateKey: '',
        icon: 'empresas',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        spiPermiso: 'tenants:ver',
        subMenu: [],
    },
    {
        key: 'jobs',
        path: '/jobs',
        title: 'Jobs',
        translateKey: '',
        icon: 'jobs',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        spiPermiso: 'jobs:ver',
        subMenu: [],
    },

    // ── SIFEN (requiere feature facturacion_electronica) ──
    {
        key: 'sifen',
        path: '',
        title: 'SIFEN',
        translateKey: '',
        icon: 'sifen',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        spiPermiso: 'sifen:ver',
        spiFeature: 'facturacion_electronica',
        subMenu: [
            {
                key: 'sifen.documentos',
                path: '/sifen/documentos',
                title: 'Documentos',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'sifen:ver',
                spiFeature: 'facturacion_electronica',
                subMenu: [],
            },
            {
                key: 'sifen.emitir',
                path: '/sifen/emitir',
                title: 'Emitir DE',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'sifen:emitir',
                spiFeature: 'facturacion_electronica',
                subMenu: [],
            },
            {
                key: 'sifen.numeracion',
                path: '/sifen/numeracion',
                title: 'Numeracion',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'sifen:ver',
                spiFeature: 'facturacion_electronica',
                subMenu: [],
            },
            {
                key: 'sifen.lotes',
                path: '/sifen/lotes',
                title: 'Lotes',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'sifen:ver',
                spiFeature: 'facturacion_electronica',
                subMenu: [],
            },
            {
                key: 'sifen.eventos',
                path: '/sifen/eventos',
                title: 'Eventos',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'sifen:ver',
                spiFeature: 'facturacion_electronica',
                subMenu: [],
            },
            {
                key: 'sifen.consultas',
                path: '/sifen/consultas',
                title: 'Consultas',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'sifen:ver',
                spiFeature: 'facturacion_electronica',
                subMenu: [],
            },
            {
                key: 'sifen.contingencia',
                path: '/sifen/contingencia',
                title: 'Contingencia',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'sifen:ver',
                spiFeature: 'facturacion_electronica',
                subMenu: [],
            },
            {
                key: 'sifen.metricas',
                path: '/sifen/metricas',
                title: 'Metricas SIFEN',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'sifen:ver',
                spiFeature: 'facturacion_electronica',
                subMenu: [],
            },
            {
                key: 'sifen.config',
                path: '/sifen/config',
                title: 'Configuracion',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'sifen:ver',
                spiFeature: 'facturacion_electronica',
                subMenu: [],
            },
        ],
    },

    // ── Banca (requiere feature conciliacion para cuentas/conciliacion/procesadoras) ──
    {
        key: 'bankingGroup',
        path: '',
        title: 'Banca',
        translateKey: '',
        icon: 'banking',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'banking.bancos',
                path: '/banking/bancos',
                title: 'Bancos',
                translateKey: '',
                icon: 'bancos',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'bancos:ver',
                subMenu: [],
            },
            {
                key: 'banking.cuentas',
                path: '/banking/cuentas',
                title: 'Cuentas Bancarias',
                translateKey: '',
                icon: 'cuentas',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiFeature: 'conciliacion',
                subMenu: [],
            },
            {
                key: 'banking.conciliacion',
                path: '/banking/conciliacion',
                title: 'Conciliacion',
                translateKey: '',
                icon: 'conciliacion',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiFeature: 'conciliacion',
                subMenu: [],
            },
            {
                key: 'banking.procesadoras',
                path: '/banking/procesadoras',
                title: 'Procesadoras',
                translateKey: '',
                icon: 'procesadoras',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiFeature: 'conciliacion',
                subMenu: [],
            },
        ],
    },

    // ── Facturacion / Billing ──
    {
        key: 'billing',
        path: '/billing',
        title: 'Facturacion',
        translateKey: '',
        icon: 'billing',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        spiPermiso: 'billing:ver',
        subMenu: [],
    },

    // ── Automatizacion ──
    {
        key: 'automationGroup',
        path: '',
        title: 'Automatizacion',
        translateKey: '',
        icon: 'automation',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'automation.alertas',
                path: '/automation/alertas',
                title: 'Alertas',
                translateKey: '',
                icon: 'alertas',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiFeature: 'alertas',
                subMenu: [],
            },
            {
                key: 'automation.anomalias',
                path: '/automation/anomalias',
                title: 'Anomalias',
                translateKey: '',
                icon: 'anomalias',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'anomalias:ver',
                spiFeature: 'anomalias',
                subMenu: [],
            },
            {
                key: 'automation.clasificacion',
                path: '/automation/clasificacion',
                title: 'Clasificacion',
                translateKey: '',
                icon: 'clasificacion',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiFeature: 'clasificacion',
                subMenu: [],
            },
            {
                key: 'automation.webhooks',
                path: '/automation/webhooks',
                title: 'Webhooks',
                translateKey: '',
                icon: 'webhooks',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiFeature: 'webhooks',
                subMenu: [],
            },
            {
                key: 'automation.apiTokens',
                path: '/automation/api-tokens',
                title: 'API Tokens',
                translateKey: '',
                icon: 'apiTokens',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiFeature: 'api_tokens',
                subMenu: [],
            },
            {
                key: 'automation.notificaciones',
                path: '/automation/notificaciones',
                title: 'Notificaciones',
                translateKey: '',
                icon: 'notificaciones',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiFeature: 'notificaciones',
                subMenu: [],
            },
        ],
    },

    // ── Metricas ──
    {
        key: 'metricas',
        path: '/metricas',
        title: 'Metricas',
        translateKey: '',
        icon: 'metricas',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        spiPermiso: 'metricas:ver',
        spiFeature: 'metricas',
        subMenu: [],
    },

    // ── Administracion ──
    {
        key: 'adminGroup',
        path: '',
        title: 'Administracion',
        translateKey: '',
        icon: 'admin',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'admin.empresas',
                path: '/admin/empresas',
                title: 'Empresas',
                translateKey: '',
                icon: 'empresas',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['super_admin'],
                subMenu: [],
            },
            {
                key: 'admin.usuarios',
                path: '/admin/usuarios',
                title: 'Usuarios',
                translateKey: '',
                icon: 'usuarios',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'usuarios:ver',
                subMenu: [],
            },
            {
                key: 'admin.roles',
                path: '/admin/roles',
                title: 'Roles',
                translateKey: '',
                icon: 'roles',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'usuarios:ver',
                spiFeature: 'roles_custom',
                subMenu: [],
            },
            {
                key: 'admin.configuracion',
                path: '/admin/configuracion',
                title: 'Configuracion',
                translateKey: '',
                icon: 'configuracion',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'configuracion:ver',
                subMenu: [],
            },
            {
                key: 'admin.sifen-plataforma',
                path: '/admin/configuracion?tab=sifen',
                title: 'SIFEN Plataforma',
                translateKey: '',
                icon: 'sifen',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'configuracion:ver',
                subMenu: [],
            },
            {
                key: 'admin.auditoria',
                path: '/admin/auditoria',
                title: 'Auditoria',
                translateKey: '',
                icon: 'auditoria',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'auditoria:ver',
                spiFeature: 'auditoria',
                subMenu: [],
            },
            {
                key: 'admin.whitelabel',
                path: '/admin/white-label',
                title: 'White Label',
                translateKey: '',
                icon: 'whitelabel',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                spiPermiso: 'tenants:editar',
                spiFeature: 'whitelabel',
                subMenu: [],
            },
            {
                key: 'admin.planes',
                path: '/admin/planes',
                title: 'Planes',
                translateKey: '',
                icon: 'planes',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['super_admin'],
                spiPermiso: 'planes:ver',
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
